### ISSUE TITLE
social media foot links

### ISSUE THREAD

**Issue by davebluke** [felixdorner/kouki#2]
Hello,

Thank you for such wonderful theme, I like it so much. I am now creating wordpress.org account only to write a review about your theme. well done indeed.

I use it for my personal blog, its still under development, but I really wish if we can have a checkbox "tick" beside each of the social media links to provide option to send user in new window which the visitor clicks on any of the social icons "Wordpress admin page>>Appearance>>Theme Options>>Footer tab: Social media links "facebook, twitter, etc." ".

Other than that, its the perfect personal blog theme. I love how clean and elegant it is.

Keep up the good work and good luck,

Amer

**Comment by felixdorner** [comment]
Hello,

thanks for your kind feedback. However, many great UX people advocate to don't manipulate the browsing experience by forcing users to open a link in a new tab/window. I agree with them. We should let the user decide how they want to open a link:

http://www.smashingmagazine.com/2008/07/should-links-open-in-new-windows/

Cheers,
Felix

**Comment by davebluke** [comment]
Hi again,
Thanks for your reply, fair enough.

Take care,
Amer
